# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CREPO_API_KEY_STAGING: ${{ secrets.CREPO_API_KEY_STAGING }}
  CREPO_API_KEY_PRODUCTION: ${{ secrets.CREPO_API_KEY_PRODUCTION }}
  NPMRC_AUTH: ${{ secrets.NPMRC_AUTH }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Use .npmrc 
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.NPMRC_AUTH }}
      - name: Package
        run: |
          npm install @cosmos/foundation@1.33.1 @cosmos/web-scoped@3.15.0 @crepo/crepo-graphql-api-node-sdk-cjs@1.6.4 @crepo/crepo-graphql-api-node-sdk-esm@1.6.4
      - run: npm ci
      - run: npm test
